In [1]:
import pandas as pd
from sklearn import tree
from sklearn import model_selection

In [2]:
dfDatosBasicos = pd.read_csv('CSV_Modificado.csv')

In [3]:
dfDatosBasicos = dfDatosBasicos.drop(['IncidntNum', 'Descript', 'Resolution', 'Address', 'Location', 
              'PdId'], 1)

In [4]:
dfDatosBasicos['Datetime'] = pd.to_datetime(dfDatosBasicos['Date'] + ' ' + dfDatosBasicos['Time'])
dfDatosBasicos = dfDatosBasicos.drop(['Date', 'Time'], 1)

dfDatosBasicos['Hour'] = dfDatosBasicos['Datetime'].apply(lambda d: d.hour + d.minute / 60)
dfDatosBasicos['DayOfWeek'] = dfDatosBasicos['Datetime'].apply(lambda d: d.weekday())
dfDatosBasicos['DayOfMonth'] = dfDatosBasicos['Datetime'].apply(lambda d: d.day)
dfDatosBasicos['Month'] = dfDatosBasicos['Datetime'].apply(lambda d: d.month)
dfDatosBasicos['Year'] = dfDatosBasicos['Datetime'].apply(lambda d: d.year)
dfDatosBasicos = dfDatosBasicos.drop('Datetime', 1)

In [5]:
dfDatosBasicos = pd.concat([dfDatosBasicos, pd.get_dummies(dfDatosBasicos['PdDistrict'])],1)
dfDatosBasicos = dfDatosBasicos.drop('PdDistrict',1)
dfDatosBasicos.head(10)

,Category,DayOfWeek,X,Y,Hour,DayOfMonth,Month,Year,BAYVIEW,CENTRAL,INGLESIDE,MISSION,NORTHERN,PARK,RICHMOND,SOUTHERN,TARAVAL,TENDERLOIN
0,NON-CRIMINAL,0,-122.421582,37.761701,14.00,19,1,2015,0,0,0,1,0,0,0,0,0,0
1,ROBBERY,6,-122.414406,37.784191,15.75,1,2,2015,0,0,0,0,0,0,0,0,0,1
2,ASSAULT,6,-122.414406,37.784191,15.75,1,2,2015,0,0,0,0,0,0,0,0,0,1
3,SECONDARY CODES,6,-122.414406,37.784191,15.75,1,2,2015,0,0,0,0,0,0,0,0,0,1
4,VANDALISM,1,-122.431119,37.800469,19.00,27,1,2015,0,0,0,0,1,0,0,0,0,0
5,NON-CRIMINAL,6,-122.451782,37.787085,16.35,1,2,2015,0,0,0,0,0,0,1,0,0,0
6,SECONDARY CODES,5,-122.374019,37.729203,21.00,31,1,2015,1,0,0,0,0,0,0,0,0,0
7,VANDALISM,5,-122.374019,37.729203,21.00,31,1,2015,1,0,0,0,0,0,0,0,0,0
8,BURGLARY,5,-122.406568,37.787809,16.15,31,1,2015,0,1,0,0,0,0,0,0,0,0
9,LARCENY/THEFT,5,-122.417295,37.786258,17.00,31,1,2015,0,1,0,0,0,0,0,0,0,0

In [6]:
catValues = dfDatosBasicos.drop('Category',1).values
labels= dfDatosBasicos['Category'].values

In [7]:
clasificador = tree.DecisionTreeClassifier()
kfold = model_selection.KFold(n_splits = 10)
resultados = model_selection.cross_val_score(clasificador, catValues, labels, cv=kfold,scoring='accuracy')
print('Precision: %f (%f)' % (resultados.mean(), resultados.std()))

Precision: 0.235859 (0.018164)

In [8]:
clasificador = tree.DecisionTreeClassifier()
clasificador.fit(catValues, labels)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [9]:
print('NON-CRIMINAL')
print(clasificador.predict([[6, -122.451782 , 37.787085, 
                     16.4, 1, 2, 2019, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]]))
print('SECONDARY CODES')
print(clasificador.predict([[5, -122.374019 , 37.729203, 
                     21.0, 31, 1, 2019, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]]))
print('VANDALISM')
print(clasificador.predict([[5, -122.374019 , 37.729203, 
                     21.0, 31, 1, 2019, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]]))
print('BURGLARY')
print(clasificador.predict([[5, -122.406568 , 37.787809, 
                     16.2, 31, 1, 2019, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]]))
print('LARCENY/THEFT')
print(clasificador.predict([[5, -122.417295 , 37.786258, 
                     17.0, 31, 1, 2019, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]]))
print('NON-CRIMINAL')
print(clasificador.predict([[0, -122.421582 , 37.761701, 
                     14.0, 19, 1, 2019, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]]))
print('ROBBERY')
print(clasificador.predict([[6, -122.414406 , 37.784191, 
                     15.8, 1, 2, 2019, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1]]))
print('ASSAULT')
print(clasificador.predict([[6, -122.414406 , 37.784191, 
                     15.8, 1, 2, 2019, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1]]))
print('SECCONDARY CODES')
print(clasificador.predict([[6, -122.414406 , 37.784191, 
                     15.8, 1, 2, 2019, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1]]))
print('VANDALISM')
print(clasificador.predict([[1, -122.431119 , 37.800469, 
                     19.0, 27, 1, 2019, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]]))

NON-CRIMINAL
['NON-CRIMINAL']
SECONDARY CODES
['SECONDARY CODES']
VANDALISM
['SECONDARY CODES']
BURGLARY
['NON-CRIMINAL']
LARCENY/THEFT
['LARCENY/THEFT']
NON-CRIMINAL
['OTHER OFFENSES']
ROBBERY
['ROBBERY']
ASSAULT
['ROBBERY']
SECCONDARY CODES
['ROBBERY']
VANDALISM
['BURGLARY']